547-  Installation layer map
sigrennesmetropole/cooperation_jn_solar pull request #222
Opened 2023-06-16 13:24 UTC by anaislet-c2c

### JIRA issue

https://jira.camptocamp.com/browse/GSREN3D-547
https://jira.camptocamp.com/browse/GSREN3D-549

### Description

Add installation layer and interactions.

### Screenshots

https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/126822753/ce6737db-674a-48c1-bf83-13f7debb64d3

2023-06-16 13:26 UTC, anaislet-c2c commented
@toni-garcia-camptocamp : There is a little bug : when the user choose a roof, the tooltip appears during 1 second before disappearing

2023-06-19 08:50 UTC, toni-garcia-camptocamp requested changes
Nice work, just some change

2023-06-19 08:50 UTC, toni-garcia-camptocamp commented on src/interactions/selectInstallationsInteraction.ts
> +import type { RennesApp } from '@/services/RennesApp'
Quand on est zoomé sur la carte et que l'on clique sur une installation au dessus d'un toit, 2 intéractions sont déclenchées:
-selectRoofInteraction 
-selectInstallationsInteraction
On passe donc à l'étape d'après car selectRoofInteraction est déclenché 
Il faut ajouter une condition dans la fonction pipe de selectRoofInteraction.
Tu peux ajouter par exemple comme condition : 
if(!selectedBuildingId || selectedBuildingId === unedefined){
 return event
}
![image](https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/121813008/604532aa-f3d5-4a3f-bc83-4cb73536e27b)

2023-06-19 08:50 UTC, toni-garcia-camptocamp commented on src/interactions/selectInstallationsInteraction.ts
> +  async pipe(event: InteractionEvent) {
Idem que pour le commentaire précédent 
Quand on clique sur un batiment , l'évenement selectInstallationInteraction est également déclenché 
Tu peux ajouter des conditions pour vérifier si installationName, installationYear et installationProduction ne sont pas vide par exemple

2023-06-19 08:50 UTC, toni-garcia-camptocamp commented on src/services/installationService.ts
> +export function updateInstallationPointCoordinates(rennesApp: RennesApp) {
updateInstallationPointCoordinates et updateDistrictPointCoordinates sont presque les mêmes 
Peux-tu factoriser la fonction en une seul stp

2023-06-19 08:50 UTC, toni-garcia-camptocamp commented on src/services/installationService.ts
> +export function addGenericListenerForUpdatePositions(rennesApp: RennesApp) {
Idem pour addGenericListenerForUpdatePositions et addGenericListenerForUpdatePositions qui sont presque pareil, peux-tu factoriser le code en une seul fonction stp

2023-06-19 08:50 UTC, toni-garcia-camptocamp commented on src/views/HomeView.vue
> +onMounted(async () => {
Pourquoi ajouter un async ici ?

2023-06-20 05:00 UTC, toni-garcia-camptocamp approved these changes
LGTM, great job :)

2023-06-20 06:46 UTC, merged